-- Convert LandingBlockType-typed columns to plain TEXT and drop the enum.
--
-- Why: each new block type previously required a Prisma migration just
-- to add an enum value (see migrations add_comparison_block_type,
-- drop_benefits_block_type, add_product_grid_block_type, etc). After
-- this migration, block types are validated in runtime by the server
-- actions against lib/blocks/registry.ts. Mirrors how ThemeSection.type
-- already works (Plan 16).
--
-- Data preservation: Postgres preserves enum textual values when
-- casting to text. Existing rows keep their type strings unchanged
-- ('HERO', 'GALLERY', 'COMPARISON', ...). No data is lost.
--
-- Rollback note: reverting requires recreating the enum and casting
-- back. Manageable but not auto-generated by `prisma migrate diff`.

ALTER TABLE "LandingBlock"
  ALTER COLUMN "type" TYPE TEXT USING "type"::text;

ALTER TABLE "TemplateBlock"
  ALTER COLUMN "type" TYPE TEXT USING "type"::text;

ALTER TABLE "PageBlock"
  ALTER COLUMN "type" TYPE TEXT USING "type"::text;

ALTER TABLE "CategoryBlock"
  ALTER COLUMN "type" TYPE TEXT USING "type"::text;

DROP TYPE "LandingBlockType";
