/** Hand-curated blocklist of the most abused disposable / temporary email
 *  domains. This is not exhaustive — the goal is to cover the easy 95%
 *  without pulling a ~3000-entry npm package. Add domains here as we see
 *  them in real abuse logs. */

const DISPOSABLE_DOMAINS = new Set<string>([
  "0clickemail.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "anonbox.net",
  "burnermail.io",
  "byom.de",
  "deadaddress.com",
  "discard.email",
  "disposable.com",
  "disposablemail.com",
  "dispostable.com",
  "dropmail.me",
  "duck.com",
  "easytrashmail.com",
  "emailfake.com",
  "emailondeck.com",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "fakemail.fr",
  "fakemail.net",
  "getairmail.com",
  "getnada.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "harakirimail.com",
  "inboxalias.com",
  "inboxbear.com",
  "instant-mail.de",
  "instantemailaddress.com",
  "kismail.ru",
  "mail-temp.com",
  "mail-temporaire.fr",
  "mail.tm",
  "mailcatch.com",
  "maildrop.cc",
  "mailfa.tk",
  "mailforspam.com",
  "mailinator.com",
  "mailinator.net",
  "mailmoat.com",
  "mailnesia.com",
  "mailnull.com",
  "mailsac.com",
  "mintemail.com",
  "mohmal.com",
  "moakt.com",
  "mytemp.email",
  "nada.email",
  "no-spam.ws",
  "nowmymail.com",
  "objectmail.com",
  "pokemail.net",
  "rapidmail.tk",
  "sharklasers.com",
  "spam4.me",
  "spambog.com",
  "spamgourmet.com",
  "spambox.us",
  "tempail.com",
  "tempinbox.com",
  "tempmail.com",
  "tempmail.de",
  "tempmail.dev",
  "tempmail.net",
  "tempmail.plus",
  "tempmail.ws",
  "tempmailer.com",
  "tempmailo.com",
  "temp-mail.io",
  "temp-mail.org",
  "throwam.com",
  "throwawaymail.com",
  "throwawayemail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
]);

export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at < 0) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  return DISPOSABLE_DOMAINS.has(domain);
}
