import { Boxes } from "lucide-react"
import type { ThemeSectionDefinition } from "../types"

export const featuredCollectionDefinition: ThemeSectionDefinition = {
  type: "FEATURED_COLLECTION",
  groups: ["PRODUCT", "COLLECTION"],
  label: "Colección destacada",
  description:
    "Muestra una colección existente o un conjunto de productos relacionados, en cuadrícula o carrusel.",
  icon: Boxes,
  fields: [
    {
      type: "text",
      key: "heading",
      label: "Título",
      placeholder: "También te puede interesar",
    },
    {
      type: "text",
      key: "subheading",
      label: "Subtítulo",
      placeholder: "Descripción breve (opcional)",
    },
    {
      type: "select",
      key: "headingAlign",
      label: "Alineación del título",
      options: [
        { value: "left", label: "Izquierda" },
        { value: "center", label: "Centrado" },
      ],
    },
    {
      type: "select",
      key: "source",
      label: "Origen de los productos",
      options: [
        { value: "collection", label: "Colección específica" },
        { value: "same_category", label: "Misma categoría" },
        { value: "manual_picks", label: "Selección manual" },
        { value: "best_sellers", label: "Más vendidos" },
        { value: "recently_viewed", label: "Vistos recientemente" },
      ],
    },
    {
      type: "category-picker",
      key: "categoryId",
      label: "Colección",
      showWhen: { field: "source", equals: "collection" },
      helpText: "Elige una colección ya creada en tu tienda.",
    },
    {
      type: "product-picker",
      key: "productIds",
      label: "Productos a mostrar",
      multiple: true,
      showWhen: { field: "source", equals: "manual_picks" },
      helpText: "Hasta 24 productos seleccionados manualmente.",
    },
    {
      type: "switch",
      key: "showViewAll",
      label: "Mostrar enlace «Ver todo»",
      showWhen: { field: "source", equals: "collection" },
      helpText: "Enlaza al final de la sección con la página de la colección.",
    },
    {
      type: "text",
      key: "viewAllText",
      label: "Texto del enlace",
      placeholder: "Ver toda la colección",
      showWhen: { field: "source", equals: "collection" },
    },
    {
      type: "number",
      key: "limit",
      label: "Cantidad máxima",
      min: 1,
      max: 24,
    },
    {
      type: "select",
      key: "layout",
      label: "Diseño",
      options: [
        { value: "grid", label: "Cuadrícula" },
        { value: "carousel", label: "Carrusel" },
      ],
    },
    {
      type: "range",
      key: "columnsDesktop",
      label: "Columnas (escritorio)",
      min: 2,
      max: 6,
      step: 1,
      defaultValue: 4,
      unit: "col",
    },
    {
      type: "select",
      key: "columnsMobile",
      label: "Columnas (móvil)",
      options: [
        { value: 1, label: "1 columna" },
        { value: 2, label: "2 columnas" },
      ],
    },
    // ── Ajustes del carrusel (solo cuando layout = carousel) ──
    {
      type: "switch",
      key: "showArrows",
      label: "Mostrar flechas",
      showWhen: { field: "layout", equals: "carousel" },
    },
    {
      type: "switch",
      key: "showDots",
      label: "Mostrar puntos (dots)",
      showWhen: { field: "layout", equals: "carousel" },
    },
    {
      type: "select",
      key: "controlsShape",
      label: "Forma de flechas y puntos",
      options: [
        { value: "round", label: "Circular" },
        { value: "square", label: "Cuadrado" },
      ],
      showWhen: { field: "layout", equals: "carousel" },
    },
  ],
  defaultContent: {
    heading: "También te puede interesar",
    subheading: "",
    headingAlign: "left",
    source: "collection",
    categoryId: null,
    productIds: [],
    showViewAll: true,
    viewAllText: "Ver toda la colección",
    limit: 8,
    layout: "carousel",
    columnsDesktop: 4,
    columnsMobile: 2,
    showArrows: true,
    showDots: true,
    controlsShape: "round",
  },
}
